### ISSUE TITLE
Steps to make the boilerplate "windows environment friendly"

### ISSUE THREAD

**Issue by leifoolsen** [antonfisher/react-express-webpack2#3]
Hello,
Thank you for a great boilerplate.

The build scripts works as expected on Linux and Mac. I have also tested the boilerplate on windows 10, and needed to apply some small modifications to package.json to build the project. 

If you would like to make the boilerplate "windows friendly", here are the steps required:

Install the following packages:
`npm i -D cross-env rimraf copyfiles`

Modify scripts:
```json
  "scripts": {
    "dev": "cross-env NODE_ENV=development node ./src/server",
    "start": "cross-env NODE_ENV=production node ./build/server",
    "prebuild": "rimraf build",
    "build": "npm run build:client && npm run build:server",
    "build:client": "cross-env NODE_ENV=production webpack -p --display-error-details --config=config/webpack.config.prod.js",
    "build:server": "copyfiles -a -u 1 src/server/** build",
    "lint": "eslint --ignore-path .gitignore --ignore-pattern node_modules -- .",
    "prettier": "prettier --ignore-path .gitignore --write './**/*.js'",
    "test": "exit 1",
    "release:patch": "npm run lint && npx standard-version -r patch && git push --follow-tags origin master",
    "release:minor": "npm run lint && npx standard-version -r minor && git push --follow-tags origin master",
    "release:major": "npm run lint && npx standard-version -r major && git push --follow-tags origin master"
  },
```

Regards
Leif Olsen

**Comment by antonfisher** [comment]
Hello Leif, thank you for the help, I will do an upgrade.

**Comment by leifoolsen** [comment]
@antonfisher The build:server script was incorrect, should be: 
`"build:server": "copyfiles -a -u 1 src/server/** build",`

**Comment by antonfisher** [comment]
I just pushed changes to the master. Thank you!
